INSERT INTO public.delivery_rates (city, neighborhood, rate) VALUES
('São Bento do Sul', 'Centro', 8.9),
('São Bento do Sul', 'Progresso', 8.9),
('São Bento do Sul', '25 de Julho', 10.5),
('São Bento do Sul', 'Alpino', 17.0),
('São Bento do Sul', 'Boehmerwald', 10.5),
('São Bento do Sul', 'Brasília', 12.0),
('São Bento do Sul', 'Centenário', 10.5),
('São Bento do Sul', 'Colonial', 10.5),
('São Bento do Sul', 'Cruzeiro', 10.5),
('São Bento do Sul', 'Industrial Sudoeste', 11.0),
('São Bento do Sul', 'Loteamento Itália', 9.5),
('São Bento do Sul', 'Mato Preto', 12.0),
('São Bento do Sul', 'Oxford', 11.0),
('São Bento do Sul', 'Parque Mariani', 9.5),
('São Bento do Sul', 'Residencial Santa Fé', 12.5),
('São Bento do Sul', 'Rio Negro', 10.0),
('São Bento do Sul', 'Schramm', 9.0),
('São Bento do Sul', 'Serra Alta', 13.0),
('São Bento do Sul', 'Dona Francisca', 15.0),
('São Bento do Sul', 'Bela Aliança', 10.0),
('São Bento do Sul', 'Campo do Meio', 10.0),
('São Bento do Sul', 'Castelo Branco', 10.0),
('São Bento do Sul', 'Estrada das Neves', 10.0),
('São Bento do Sul', 'Estrada dos Bugres', 10.0),
('São Bento do Sul', 'Lençol', 10.0),
('São Bento do Sul', 'Rio Natal', 10.0),
('São Bento do Sul', 'Rio Represo', 10.0),
('São Bento do Sul', 'Rio Vermelho Estação', 10.0),
('São Bento do Sul', 'Rio Vermelho Povoado', 10.0),
('São Bento do Sul', 'Sertãozinho', 10.0),
('São Bento do Sul', 'Serra Alta I', 13.0),
('São Bento do Sul', 'Serra Alta II', 13.0),
('São Bento do Sul', 'Rio Vermelho', 12.0),
('São Bento do Sul', 'Oxford I', 11.0),
('São Bento do Sul', 'Oxford II', 11.0),
('Rio Negrinho', 'Ceramarte', 10.0),
('Rio Negrinho', 'Alegre', 10.0),
('Rio Negrinho', 'Bairro Preto', 10.0),
('Rio Negrinho', 'Barro Preto', 10.0),
('Rio Negrinho', 'Bela Vista', 10.0),
('Rio Negrinho', 'Campo Lençol', 10.0),
('Rio Negrinho', 'Centro', 10.0),
('Rio Negrinho', 'Colônia Olsen', 10.0),
('Rio Negrinho', 'Cruzeiro', 10.0),
('Rio Negrinho', 'Industrial Norte', 10.0),
('Rio Negrinho', 'Industrial Sul', 10.0),
('Rio Negrinho', 'Jardim Hantschel', 10.0),
('Rio Negrinho', 'Pinheirinho', 10.0),
('Rio Negrinho', 'Quitandinha', 10.0),
('Rio Negrinho', 'Rio Casa de Pedra', 10.0),
('Rio Negrinho', 'Rio Preto', 10.0),
('Rio Negrinho', 'Rio dos Bugres', 10.0),
('Rio Negrinho', 'Serro Azul', 10.0),
('Rio Negrinho', 'São Pedro', 10.0),
('Rio Negrinho', 'São Rafael', 10.0),
('Rio Negrinho', 'Vila Nova', 10.0),
('Rio Negrinho', 'Vista Alegre', 10.0),
('Rio Negrinho', 'Volta Grande', 10.0),
('Campo Alegre', 'Avenquinha', 10.0),
('Campo Alegre', 'Bateias de Baixo', 10.0),
('Campo Alegre', 'Bateias de Cima', 10.0),
('Campo Alegre', 'Belo Horizonte', 10.0),
('Campo Alegre', 'Cascata', 10.0),
('Campo Alegre', 'Cascatas', 10.0),
('Campo Alegre', 'Centro', 10.0),
('Campo Alegre', 'Corredeiras', 10.0),
('Campo Alegre', 'Fragosos', 10.0),
('Campo Alegre', 'Lajeado', 10.0),
('Campo Alegre', 'Mato Limpo', 10.0),
('Campo Alegre', 'Pinhais', 10.0),
('Campo Alegre', 'Povoado de Fragosos', 10.0),
('Campo Alegre', 'Ribeirão do Meio', 10.0),
('Campo Alegre', 'Rio Represo', 10.0),
('Campo Alegre', 'Rio do Bugre', 10.0),
('Campo Alegre', 'Saltinho', 10.0),
('Campo Alegre', 'Santo Antônio', 10.0),
('Campo Alegre', 'São Miguel', 10.0),
('Campo Alegre', 'Vila Novo Mundo', 10.0),
('Corupá', 'Ano Bom', 10.0),
('Corupá', 'Bomplandt', 10.0),
('Corupá', 'Caminho Pequeno', 10.0),
('Corupá', 'Centro', 10.0),
('Corupá', 'Faxinal', 10.0),
('Corupá', 'Itapocu', 10.0),
('Corupá', 'Izabel', 10.0),
('Corupá', 'João Tozini', 10.0),
('Corupá', 'Pedra de Amolar', 10.0),
('Corupá', 'Poço D''Anta', 10.0),
('Corupá', 'Putinga', 10.0),
('Corupá', 'Rio Correa', 10.0),
('Corupá', 'Rio Feio', 10.0),
('Corupá', 'Rio Novo', 10.0),
('Corupá', 'Rio Paulo', 10.0),
('Corupá', 'Rio da Veada', 10.0),
('Corupá', 'Seminário', 10.0),
('Corupá', 'XV de Novembro', 10.0),
('Mafra', 'Augusta Vitória', 10.0),
('Mafra', 'Autódromo', 10.0),
('Mafra', 'Avencal São Sebastião', 10.0),
('Mafra', 'Avencal de Cima', 10.0),
('Mafra', 'Avencal do Meio', 10.0),
('Mafra', 'Bairro do Autódromo', 10.0),
('Mafra', 'Bela Vista do Sul', 10.0),
('Mafra', 'Bituvinha', 10.0),
('Mafra', 'Butiá dos Tabordas', 10.0),
('Mafra', 'Campina Konkel', 10.0),
('Mafra', 'Campo da Lança', 10.0),
('Mafra', 'Caçador', 10.0),
('Mafra', 'Centro I - Baixada', 10.0),
('Mafra', 'Centro II - Alto de Mafra', 10.0),
('Mafra', 'Centro III Monte Alegre', 10.0),
('Mafra', 'Espigão do Bugre', 10.0),
('Mafra', 'Faxinal', 10.0),
('Mafra', 'Fazenda Potreiro', 10.0),
('Mafra', 'General Brito', 10.0),
('Mafra', 'Imbuial', 10.0),
('Mafra', 'Jardim América', 10.0),
('Mafra', 'Jardim Novo Horizonte', 10.0),
('Mafra', 'Jardim do Moinho', 10.0),
('Mafra', 'Maurício Caillet', 10.0),
('Mafra', 'Nossa Senhora Aparecida', 10.0),
('Mafra', 'Passo', 10.0),
('Mafra', 'Restinga', 10.0),
('Mafra', 'Rio Preto', 10.0),
('Mafra', 'Rio da Areia', 10.0),
('Mafra', 'Rio da Areia de Baixo', 10.0),
('Mafra', 'Rio da Areia de Cima', 10.0),
('Mafra', 'Rio do Cedro', 10.0),
('Mafra', 'Saltinho do Canivete', 10.0),
('Mafra', 'São Lourenço', 10.0),
('Mafra', 'Vila Argentina', 10.0),
('Mafra', 'Vila Buenos Aires', 10.0),
('Mafra', 'Vila Clementina', 10.0),
('Mafra', 'Vila Edson Luis', 10.0),
('Mafra', 'Vila Ferroviária', 10.0),
('Mafra', 'Vila Formosa', 10.0),
('Mafra', 'Vila Industrial', 10.0),
('Mafra', 'Vila Ivete', 10.0),
('Mafra', 'Vila Nova', 10.0),
('Mafra', 'Vila Ruthes', 10.0),
('Mafra', 'Vila Solidariedade', 10.0),
('Mafra', 'Vila Velha', 10.0),
('Mafra', 'Vila das Flores', 10.0),
('Mafra', 'Vilinha', 10.0),
('Mafra', 'Vista Alegre', 10.0),
('Piên', 'Aterrado Alto', 10.0),
('Piên', 'Avencal', 10.0),
('Piên', 'Boa Vista', 10.0),
('Piên', 'Cachoeirinha', 10.0),
('Piên', 'Campina dos Crespins', 10.0),
('Piên', 'Campina dos Maia', 10.0),
('Piên', 'Campo Novo', 10.0),
('Piên', 'Centro', 10.0),
('Piên', 'Cerro Verde', 10.0),
('Piên', 'Gramados', 10.0),
('Piên', 'Lageado', 10.0),
('Piên', 'Letreiro', 10.0),
('Piên', 'Mosquito', 10.0),
('Piên', 'Palmito', 10.0),
('Piên', 'Palmito de Cima', 10.0),
('Piên', 'Picacinho', 10.0),
('Piên', 'Pocinho', 10.0),
('Piên', 'Poço Frio', 10.0),
('Piên', 'Poço Frio dos Moreiras', 10.0),
('Piên', 'Quicé', 10.0),
('Piên', 'Trigolândia', 10.0),
('Piên', 'Vermelhinho', 10.0),
('Rio Negro', 'Bairro Alto', 10.0),
('Rio Negro', 'Bairro do Seminário', 10.0),
('Rio Negro', 'Bom Jesus', 10.0),
('Rio Negro', 'Bom Jesus do Rio Negro', 10.0),
('Rio Negro', 'Campina dos Andrades', 10.0),
('Rio Negro', 'Campo do Gado', 10.0),
('Rio Negro', 'Centro', 10.0),
('Rio Negro', 'Estação Nova', 10.0),
('Rio Negro', 'Fazendinha', 10.0),
('Rio Negro', 'Jardim Zelinda', 10.0),
('Rio Negro', 'Lageado dos Vieiras', 10.0),
('Rio Negro', 'Maitaca', 10.0),
('Rio Negro', 'Passa Três', 10.0),
('Rio Negro', 'Passo do Valo', 10.0),
('Rio Negro', 'Retiro', 10.0),
('Rio Negro', 'Roseira', 10.0),
('Rio Negro', 'Seminário', 10.0),
('Rio Negro', 'Sítio dos Rauen', 10.0),
('Rio Negro', 'Tijuco Preto', 10.0),
('Rio Negro', 'Vila Militar', 10.0),
('Rio Negro', 'Vila Paraná', 10.0),
('Rio Negro', 'Vila Paraíso', 10.0),
('Rio Negro', 'Volta Grande', 10.0)
ON CONFLICT (city, neighborhood) DO UPDATE SET rate = EXCLUDED.rate;
