import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey =
  process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Credentials missing");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const dataMap = {
  "São Bento do Sul": [
    { neighborhood: "Centro", rate: 8.9 },
    { neighborhood: "Progresso", rate: 8.9 },
    { neighborhood: "25 de Julho", rate: 10.5 },
    { neighborhood: "Alpino", rate: 17.0 },
    { neighborhood: "Boehmerwald", rate: 10.5 },
    { neighborhood: "Brasília", rate: 12.0 },
    { neighborhood: "Centenário", rate: 10.5 },
    { neighborhood: "Colonial", rate: 10.5 },
    { neighborhood: "Cruzeiro", rate: 10.5 },
    { neighborhood: "Industrial Sudoeste", rate: 11.0 },
    { neighborhood: "Loteamento Itália", rate: 9.5 },
    { neighborhood: "Mato Preto", rate: 12.0 },
    { neighborhood: "Oxford", rate: 11.0 },
    { neighborhood: "Parque Mariani", rate: 9.5 },
    { neighborhood: "Residencial Santa Fé", rate: 12.5 },
    { neighborhood: "Rio Negro", rate: 10.0 },
    { neighborhood: "Schramm", rate: 9.0 },
    { neighborhood: "Serra Alta", rate: 13.0 },
    { neighborhood: "Dona Francisca", rate: 15.0 },
    { neighborhood: "Bela Aliança", rate: 10.0 },
    { neighborhood: "Campo do Meio", rate: 10.0 },
    { neighborhood: "Castelo Branco", rate: 10.0 },
    { neighborhood: "Estrada das Neves", rate: 10.0 },
    { neighborhood: "Estrada dos Bugres", rate: 10.0 },
    { neighborhood: "Lençol", rate: 10.0 },
    { neighborhood: "Rio Natal", rate: 10.0 },
    { neighborhood: "Rio Represo", rate: 10.0 },
    { neighborhood: "Rio Vermelho Estação", rate: 10.0 },
    { neighborhood: "Rio Vermelho Povoado", rate: 10.0 },
    { neighborhood: "Sertãozinho", rate: 10.0 },
    { neighborhood: "Serra Alta I", rate: 13.0 },
    { neighborhood: "Serra Alta II", rate: 13.0 },
    { neighborhood: "Rio Vermelho", rate: 12.0 },
    { neighborhood: "Oxford I", rate: 11.0 },
    { neighborhood: "Oxford II", rate: 11.0 },
  ],
  "Rio Negrinho": [
    "Ceramarte",
    "Alegre",
    "Bairro Preto",
    "Barro Preto",
    "Bela Vista",
    "Campo Lençol",
    "Centro",
    "Colônia Olsen",
    "Cruzeiro",
    "Industrial Norte",
    "Industrial Sul",
    "Jardim Hantschel",
    "Pinheirinho",
    "Quitandinha",
    "Rio Casa de Pedra",
    "Rio Preto",
    "Rio dos Bugres",
    "Serro Azul",
    "São Pedro",
    "São Rafael",
    "Vila Nova",
    "Vista Alegre",
    "Volta Grande",
  ],
  "Campo Alegre": [
    "Avenquinha",
    "Bateias de Baixo",
    "Bateias de Cima",
    "Belo Horizonte",
    "Cascata",
    "Cascatas",
    "Centro",
    "Corredeiras",
    "Fragosos",
    "Lajeado",
    "Mato Limpo",
    "Pinhais",
    "Povoado de Fragosos",
    "Ribeirão do Meio",
    "Rio Represo",
    "Rio do Bugre",
    "Saltinho",
    "Santo Antônio",
    "São Miguel",
    "Vila Novo Mundo",
  ],
  Corupá: [
    "Ano Bom",
    "Bomplandt",
    "Caminho Pequeno",
    "Centro",
    "Faxinal",
    "Itapocu",
    "Izabel",
    "João Tozini",
    "Pedra de Amolar",
    "Poço D'Anta",
    "Putinga",
    "Rio Correa",
    "Rio Feio",
    "Rio Novo",
    "Rio Paulo",
    "Rio da Veada",
    "Seminário",
    "XV de Novembro",
  ],
  Mafra: [
    "Augusta Vitória",
    "Autódromo",
    "Avencal São Sebastião",
    "Avencal de Cima",
    "Avencal do Meio",
    "Bairro do Autódromo",
    "Bela Vista do Sul",
    "Bituvinha",
    "Butiá dos Tabordas",
    "Campina Konkel",
    "Campo da Lança",
    "Caçador",
    "Centro I - Baixada",
    "Centro II - Alto de Mafra",
    "Centro III Monte Alegre",
    "Espigão do Bugre",
    "Faxinal",
    "Fazenda Potreiro",
    "General Brito",
    "Imbuial",
    "Jardim América",
    "Jardim Novo Horizonte",
    "Jardim do Moinho",
    "Maurício Caillet",
    "Nossa Senhora Aparecida",
    "Passo",
    "Restinga",
    "Rio Preto",
    "Rio da Areia",
    "Rio da Areia de Baixo",
    "Rio da Areia de Cima",
    "Rio do Cedro",
    "Saltinho do Canivete",
    "São Lourenço",
    "Vila Argentina",
    "Vila Buenos Aires",
    "Vila Clementina",
    "Vila Edson Luis",
    "Vila Ferroviária",
    "Vila Formosa",
    "Vila Industrial",
    "Vila Ivete",
    "Vila Nova",
    "Vila Ruthes",
    "Vila Solidariedade",
    "Vila Velha",
    "Vila das Flores",
    "Vilinha",
    "Vista Alegre",
  ],
  Piên: [
    "Aterrado Alto",
    "Avencal",
    "Boa Vista",
    "Cachoeirinha",
    "Campina dos Crespins",
    "Campina dos Maia",
    "Campo Novo",
    "Centro",
    "Cerro Verde",
    "Gramados",
    "Lageado",
    "Letreiro",
    "Mosquito",
    "Palmito",
    "Palmito de Cima",
    "Picacinho",
    "Pocinho",
    "Poço Frio",
    "Poço Frio dos Moreiras",
    "Quicé",
    "Trigolândia",
    "Vermelhinho",
  ],
  "Rio Negro": [
    "Bairro Alto",
    "Bairro do Seminário",
    "Bom Jesus",
    "Bom Jesus do Rio Negro",
    "Campina dos Andrades",
    "Campo do Gado",
    "Centro",
    "Estação Nova",
    "Fazendinha",
    "Jardim Zelinda",
    "Lageado dos Vieiras",
    "Maitaca",
    "Passa Três",
    "Passo do Valo",
    "Retiro",
    "Roseira",
    "Seminário",
    "Sítio dos Rauen",
    "Tijuco Preto",
    "Vila Militar",
    "Vila Paraná",
    "Vila Paraíso",
    "Volta Grande",
  ],
};

const rows: any[] = [];
for (const [city, neighborhoods] of Object.entries(dataMap)) {
  for (const n of neighborhoods) {
    const name = typeof n === "string" ? n : n.neighborhood;
    const rate = typeof n === "string" ? 10.0 : n.rate;
    rows.push({ city, neighborhood: name, rate });
  }
}

async function run() {
  console.log(`Upserting ${rows.length} rows...`);
  const { error } = await supabase
    .from("delivery_rates")
    .upsert(rows, { onConflict: "city,neighborhood" });

  if (error) {
    console.error("Error upserting:", error);
    process.exit(1);
  }
  console.log("Sync complete!");
}

run();
