/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminLoginRouteImport } from './routes/admin-login.tsx'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminConfigIndexRouteImport } from './routes/admin/config/index'
import { Route as AdminConfigSiteRouteImport } from './routes/admin.config.site'
import { Route as AdminConfigTaxasRouteImport } from './routes/admin/config/taxas'
import { Route as AdminFinanceiroIndexRouteImport } from './routes/admin/financeiro/index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminRelatoriosIndexRouteImport } from './routes/admin/relatorios/index'
import { Route as AdminRelatoriosKpiRouteImport } from './routes/admin/relatorios/kpi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/_authenticated/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigIndexRoute = AdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigSiteRoute = AdminConfigSiteRouteImport.update({
  id: '/config/site',
  path: '/config/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigTaxasRoute = AdminConfigTaxasRouteImport.update({
  id: '/config/taxas',
  path: '/config/taxas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroIndexRoute = AdminFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminRelatoriosIndexRoute = AdminRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosKpiRoute = AdminRelatoriosKpiRouteImport.update({
  id: '/relatorios/kpi',
  path: '/relatorios/kpi',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/config/site': typeof AdminConfigSiteRoute
  '/admin/config/taxas': typeof AdminConfigTaxasRoute
  '/admin/relatorios/kpi': typeof AdminRelatoriosKpiRoute
  '/admin/config/': typeof AdminConfigIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/relatorios/': typeof AdminRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/config/site': typeof AdminConfigSiteRoute
  '/admin/config/taxas': typeof AdminConfigTaxasRoute
  '/admin/relatorios/kpi': typeof AdminRelatoriosKpiRoute
  '/admin/config': typeof AdminConfigIndexRoute
  '/admin/financeiro': typeof AdminFinanceiroIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/relatorios': typeof AdminRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/config/site': typeof AdminConfigSiteRoute
  '/admin/config/taxas': typeof AdminConfigTaxasRoute
  '/admin/relatorios/kpi': typeof AdminRelatoriosKpiRoute
  '/admin/config/': typeof AdminConfigIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/relatorios/': typeof AdminRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/perfil'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/config/site'
    | '/admin/config/taxas'
    | '/admin/relatorios/kpi'
    | '/admin/config/'
    | '/admin/financeiro/'
    | '/admin/pedidos/'
    | '/admin/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/perfil'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin'
    | '/admin/config/site'
    | '/admin/config/taxas'
    | '/admin/relatorios/kpi'
    | '/admin/config'
    | '/admin/financeiro'
    | '/admin/pedidos'
    | '/admin/relatorios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/_authenticated/perfil'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/config/site'
    | '/admin/config/taxas'
    | '/admin/relatorios/kpi'
    | '/admin/config/'
    | '/admin/financeiro/'
    | '/admin/pedidos/'
    | '/admin/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/': {
      id: '/admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AdminConfigIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/site': {
      id: '/admin/config/site'
      path: '/config/site'
      fullPath: '/admin/config/site'
      preLoaderRoute: typeof AdminConfigSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/taxas': {
      id: '/admin/config/taxas'
      path: '/config/taxas'
      fullPath: '/admin/config/taxas'
      preLoaderRoute: typeof AdminConfigTaxasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/': {
      id: '/admin/financeiro/'
      path: '/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminFinanceiroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/relatorios/': {
      id: '/admin/relatorios/'
      path: '/relatorios'
      fullPath: '/admin/relatorios/'
      preLoaderRoute: typeof AdminRelatoriosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/kpi': {
      id: '/admin/relatorios/kpi'
      path: '/relatorios/kpi'
      fullPath: '/admin/relatorios/kpi'
      preLoaderRoute: typeof AdminRelatoriosKpiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfigSiteRoute: typeof AdminConfigSiteRoute
  AdminConfigTaxasRoute: typeof AdminConfigTaxasRoute
  AdminRelatoriosKpiRoute: typeof AdminRelatoriosKpiRoute
  AdminConfigIndexRoute: typeof AdminConfigIndexRoute
  AdminFinanceiroIndexRoute: typeof AdminFinanceiroIndexRoute
  AdminRelatoriosIndexRoute: typeof AdminRelatoriosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConfigSiteRoute: AdminConfigSiteRoute,
  AdminConfigTaxasRoute: AdminConfigTaxasRoute,
  AdminRelatoriosKpiRoute: AdminRelatoriosKpiRoute,
  AdminConfigIndexRoute: AdminConfigIndexRoute,
  AdminFinanceiroIndexRoute: AdminFinanceiroIndexRoute,
  AdminRelatoriosIndexRoute: AdminRelatoriosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
